FROM dunglas/frankenphp:1-php8.3

RUN apt-get update && apt-get install -y \
    git curl zip unzip libzip-dev libpng-dev libonig-dev \
    && rm -rf /var/lib/apt/lists/*

RUN install-php-extensions pdo_mysql mbstring zip exif pcntl gd bcmath

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /app
COPY ./backend .

RUN composer install --no-dev --optimize-autoloader

RUN chown -R www-data:www-data storage bootstrap/cache

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

COPY ./backend/start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

# 8. Порт и запуск
EXPOSE 80

CMD ["/usr/local/bin/start.sh"]